const $=s=>document.querySelector(s);const audio=$('#audio'),music=$('#music');let opened=false;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
if(!reduced) document.body.classList.add('motion');
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});
function syncMusic(){music.setAttribute('aria-pressed',String(!audio.paused));music.setAttribute('aria-label',audio.paused?'Reproducir música':'Pausar música');music.firstElementChild.textContent=audio.paused?'♫':'Ⅱ'}
audio.addEventListener('play',syncMusic);audio.addEventListener('pause',syncMusic);audio.addEventListener('error',()=>{music.setAttribute('aria-label','Volver a intentar reproducir música')});
$('#open').addEventListener('click',()=>{if(opened)return;opened=true;audio.volume=.65;audio.play().catch(syncMusic);$('#cover').classList.add('opening');$('#invitation').inert=false;music.hidden=false;window.scrollTo(0,0);setTimeout(()=>{$('#cover').hidden=true;document.body.classList.remove('locked');document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));$('#music').focus({preventScroll:true})},reduced?0:1200)});
music.addEventListener('click',()=>{if(audio.paused)audio.play().catch(syncMusic);else audio.pause()});
const target=new Date('2026-10-23T00:00:00-05:00').getTime();function tick(){const diff=Math.max(0,target-Date.now());const vals=[Math.floor(diff/86400000),Math.floor(diff/3600000)%24,Math.floor(diff/60000)%60,Math.floor(diff/1000)%60];['days','hours','minutes','seconds'].forEach((id,i)=>$('#'+id).textContent=String(vals[i]).padStart(2,'0'));if(!diff)$('#count-caption').textContent='¡Llegó el día de mis XV años!'}tick();setInterval(tick,1000);
const cal=$('#calendar-days');for(let i=0;i<4;i++)cal.append(document.createElement('span'));for(let d=1;d<=31;d++){const s=document.createElement('span');s.textContent=d;if(d===23){s.className='chosen';s.setAttribute('aria-label','23 de octubre, mis XV años')}cal.append(s)}
$('#gift-open').addEventListener('click',()=>$('#gift-dialog').showModal());document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.close').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}})});
$('#copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText('971486394');$('#copy-status').textContent='Número copiado: 971 486 394'}catch{$('#copy-status').textContent='Mantén pulsado el número para copiarlo: 971 486 394'}});
document.querySelectorAll('[data-photo]').forEach(b=>b.addEventListener('click',()=>{$('#large-photo').src=b.querySelector('img').src;$('#large-photo').alt=b.querySelector('img').alt;$('#photo-dialog').showModal()}));
if(!reduced){for(let i=0;i<18;i++){const s=document.createElement('i');s.className='spark';s.style.left=Math.random()*100+'%';s.style.top=Math.random()*100+'%';s.style.animationDelay=Math.random()*7+'s';s.setAttribute('aria-hidden','true');$('.hero').append(s)}}
